### ISSUE TITLE
Cannot reproduce the results of Table 1(a) for OnDA-Hybrid Switch for 200mm rain condition

### ISSUE THREAD

**Issue by Sumanth181099** [theo2021/OnDA#4]
We followed the instructions given in the ReadMe file and tried to reproduce the results of Table 1(a) for online hybrid switch settings. As can be seen from the image, we can reproduce the results for all the rain conditions with max ~1% difference, but for 200mm rain condition the difference between the reported and reproduced is around 10%. Any help regarding this issue will be really appreciated.
![OnDA_reproduced](https://github.com/theo2021/OnDA/assets/65185434/c16dfe36-3e67-4eee-9ea9-a0bd4e91adc4)

**Comment by theo2021** [comment]
Hi, just to double check, did you run with the [[1024, 512] resolution?](https://github.com/theo2021/OnDA/blob/fb4bc15a8a8e4185486d9c2e1ce2062670d4308c/configs/hybrid_switch.yml#L12)

**Comment by Sumanth181099** [comment]
Thank you for your reply. 
However, weights and biases printed the last validation values mIoU values. Using figure 4 I deduced that, it is close to the reported score in the bold part of the graph for every setting. You may please close this issue.
